CREATE DATABASE AuditPracticeDB;
GO

USE AuditPracticeDB;
GO

-- Main table
CREATE TABLE Employee (
	EmpID INT PRIMARY KEY,
	EmpName VARCHAR(100),
	Salary DECIMAL(10,2)
);

-- Audit table
CREATE TABLE EmployeeAudit (
	AuditID INT IDENTITY PRIMARY KEY,
	EmpID INT,
	ActionType VARCHAR(10),
	OldSalary DECIMAL(10,2),
	NewSalary DECIMAL(10,2),
	ActionDate DATETIME DEFAULT GETDATE()
);

-- STORED PROCEDURES

-- INSERT PROCEDURE
CREATE PROCEDURE InsertEmployee
	@EmpID INT,
	@EmpName VARCHAR(100),
	@Salary DECIMAL(10,2)
AS
BEGIN
	INSERT INTO Employee
	VALUES (@EmpID, @EmpName, @Salary);
END;

-- SELECT PROCEDURE
CREATE PROCEDURE GetAllEmployees
AS
BEGIN
	SELECT * FROM Employee;
END;


-- UPDATE PROCEDURE
CREATE PROCEDURE UpdateEmployeeSalary
	@EmpID INT,
	@NewSalary DECIMAL(10,2)
AS
BEGIN
	UPDATE Employee
	SET Salary = @NewSalary
	WHERE EmpID = @EmpID;
END;


-- DELETE PROCEDURE
CREATE PROCEDURE DeleteEmployee
	@EmpID INT
AS
BEGIN
	DELETE FROM Employee
	WHERE EmpID = @EmpID;
END;


-- TRIGGERS (INSERT, UPDATE & DELETE)
CREATE TRIGGER trg_Employee_Audit
ON Employee
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
	-- INSERT
	INSERT INTO EmployeeAudit (EmpID, ActionType, NewSalary)
	SELECT EmpID, 'INSERT', Salary
	FROM inserted
	WHERE EmpID NOT IN (SELECT EmpID FROM deleted);

	-- DELETE
	INSERT INTO EmployeeAudit (EmpID, ActionType, OldSalary)
	SELECT EmpID, 'DELETE', Salary
	FROM deleted
	WHERE EmpID NOT IN (SELECT EmpID FROM inserted);

	-- UPDATE
	INSERT INTO EmployeeAudit (EmpID, ActionType, OldSalary, NewSalary)
	SELECT d.EmpID, 'UPDATE', d.Salary, i.Salary
	FROM deleted d
	JOIN inserted i
	ON d.EmpID = i.EmpID;
END;

-- INSERT using stored procedure
EXEC InsertEmployee 1, 'Rahul', 40000;
EXEC InsertEmployee 2, 'Anita', 50000;

-- SELECT using stored procedure
EXEC GetAllEmployees;

-- UPDATE using stored procedure
EXEC UpdateEmployeeSalary 1, 45000;

-- DELETE using stored procedure
EXEC DeleteEmployee 2;

-- View audit records generated by trigger
SELECT * FROM EmployeeAudit;
